services:
  - type: web
    name: yuanxing
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
    aptPackages:
      - tesseract-ocr
      - tesseract-ocr-chi-tra